### Create new user
POST http://localhost:3030/users
Content-Type: application/json

{
  "email": "your_email",
  "password": "your_password"
}

### Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "email": "your_email",
  "password": "your_password",
  "strategy": "local"
}
